#!/bin/bash
# =============================================================================
# ai-dev-sandbox — Host Entrypoint Wrapper
# =============================================================================
# Runs in the HOST Docker container (ai-dev-sandbox-host), before the Firecracker
# VMM starts.
#
# Responsibilities:
#   1. Write API keys and config from host env vars into /workspace/.sandbox.env
#      — the guest VM's .bash_profile reads this file when launching the
#        ai-dev-sandbox container via --env-file
#   2. Hand off to firecracker-base's original entrypoint.sh
#
# Why this approach for secrets:
#   Firecracker has MMDS (metadata service) but it requires kernel-side
#   configuration in the guest.  Writing to the shared workspace ext4 volume
#   is simpler, reliable, and already the established data-sharing channel
#   between host and guest in this setup.
#   The .sandbox.env file is chmod 600 so it's only readable by UID 1000
#   (the sandbox user).
# =============================================================================

set -euo pipefail

HOST_WORKSPACE="${HOST_WORKSPACE:-/workspace}"

# ─── Write sandbox env file ───────────────────────────────────────────────────
write_sandbox_env() {
    mkdir -p "$HOST_WORKSPACE"

    cat > "$HOST_WORKSPACE/.sandbox.env" << EOF
# =============================================================================
# .sandbox.env — auto-generated by ai-dev-sandbox host on $(date -u +"%Y-%m-%dT%H:%M:%SZ")
# DO NOT EDIT — this file is overwritten each time the VM starts.
# Set values in your .env file or pass them via docker run -e / docker compose.
# =============================================================================

# ─── AI API Keys ─────────────────────────────────────────────────────────────
ANTHROPIC_API_KEY=${ANTHROPIC_API_KEY:-}
OPENAI_API_KEY=${OPENAI_API_KEY:-}
GOOGLE_API_KEY=${GOOGLE_API_KEY:-}
GEMINI_API_KEY=${GEMINI_API_KEY:-}
GITHUB_TOKEN=${GITHUB_TOKEN:-}

# ─── Ollama - Host machine ────────────────────────────────────────────────────
# 172.16.0.1 is the TAP gateway — i.e. the Docker host as seen from the guest.
# If Ollama runs on the host machine, this default just works.
OLLAMA_HOST=${OLLAMA_HOST:-http://172.16.0.1:11434}
OLLAMA_MODEL=${OLLAMA_MODEL:-llama3.2}

# ─── Ollama - Lan Network Egress policy for guest firewall ─────────────────────
# Allow one LAN target while blocking other RFC1918 ranges.
# If Ollama runs on another machine in the same network, add its IP to EGRESS_ALLOW_IP.
EGRESS_ALLOW_IP=${EGRESS_ALLOW_IP:-}
EGRESS_ALLOW_TCP_PORTS=${EGRESS_ALLOW_TCP_PORTS:-11434}

# ─── Voice ────────────────────────────────────────────────────────────────────
WHISPER_MODEL=${WHISPER_MODEL:-base.en}
PIPER_VOICE=${PIPER_VOICE:-en_US-amy-medium}
VOICE_AI_TOOL=${VOICE_AI_TOOL:-claude}

# ─── Audio (PulseAudio over TCP) ─────────────────────────────────────────────
# Voice mode requires PulseAudio TCP on the host.  Enable with:
#   pactl load-module module-native-protocol-tcp auth-ip-acl="127.0.0.1;172.16.0.0/24" auth-anonymous=1
# PULSE_SERVER tells PulseAudio clients inside the VM to connect via TAP gateway.
PULSE_SERVER=${PULSE_SERVER:-tcp:172.16.0.1:4713}

# ─── Terminal ─────────────────────────────────────────────────────────────────
TERM=xterm-256color
COLORTERM=truecolor
EDITOR=${EDITOR:-vim}
VISUAL=${VISUAL:-vim}
EOF

    # Only sandbox user (UID 1000) should read this — it contains secrets
    chmod 600 "$HOST_WORKSPACE/.sandbox.env"
}

write_sandbox_env
echo "[ai-dev-sandbox-host] Sandbox env written to $HOST_WORKSPACE/.sandbox.env"

# ─── Enable IP forwarding for TAP/NAT ─────────────────────────────────────
# These cannot be set via Docker's sysctls: directive when using
# network_mode: host, so we set them imperatively here.
echo "[ai-dev-sandbox-host] Enabling IP forwarding for TAP/NAT..."
sysctl -w net.ipv4.ip_forward=1 >/dev/null 2>&1 || true
sysctl -w net.ipv4.conf.all.forwarding=1 >/dev/null 2>&1 || true
sysctl -w net.ipv4.conf.all.rp_filter=0 >/dev/null 2>&1 || true
sysctl -w net.ipv4.conf.default.rp_filter=0 >/dev/null 2>&1 || true

# ─── Hand off to firecracker-base entrypoint ─────────────────────────────────
exec /usr/local/bin/entrypoint.sh "$@"
